// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4nhSdwMDRocOliYKnIqPfRfjmZ4vwKbo',
    appId: '1:511268448791:web:0306b85495df07cfea8a52',
    messagingSenderId: '511268448791',
    projectId: 'mafia-vs-civilans',
    authDomain: 'mafia-vs-civilans.firebaseapp.com',
    storageBucket: 'mafia-vs-civilans.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1wBK6kFGzllKlGZa733tYCK9Wb5L2ALg',
    appId: '1:511268448791:android:26904f0a9039325aea8a52',
    messagingSenderId: '511268448791',
    projectId: 'mafia-vs-civilans',
    storageBucket: 'mafia-vs-civilans.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqRs-ogJ4T0CAaOBMPeTYqIAEEXUm_1DM',
    appId: '1:511268448791:ios:8745879868502a88ea8a52',
    messagingSenderId: '511268448791',
    projectId: 'mafia-vs-civilans',
    storageBucket: 'mafia-vs-civilans.appspot.com',
    iosBundleId: 'com.example.mafiaCitizen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqRs-ogJ4T0CAaOBMPeTYqIAEEXUm_1DM',
    appId: '1:511268448791:ios:ed2a01743b17aee7ea8a52',
    messagingSenderId: '511268448791',
    projectId: 'mafia-vs-civilans',
    storageBucket: 'mafia-vs-civilans.appspot.com',
    iosBundleId: 'com.example.mafiaCitizen.RunnerTests',
  );
}
